autoscaling:
  enabled: false
  
replicaCount: 1

image:
  repository: registry.home.lab/dockerhub-proxy/linuxserver/smokeping
  pullPolicy: IfNotPresent
  tag: "version-2.7.3-r5"

imagePullSecrets:
  - name: registry-harbor-sa

serviceAccount:
  create: false

service:
  enabled: true
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: homelab-ca-issuer
    nginx.ingress.kubernetes.io/auth-url: |-
      http://ak-outpost-smokeping.smokeping.svc.cluster.local:9000/outpost.goauthentik.io/auth/nginx

    nginx.ingress.kubernetes.io/auth-signin: |-
      https://smokeping.home.lab/outpost.goauthentik.io/start?rd=$escaped_request_uri
    
    nginx.ingress.kubernetes.io/auth-response-headers: |-
      Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid
    
    nginx.ingress.kubernetes.io/auth-snippet: |
      proxy_set_header X-Forwarded-Host $http_host;

  hosts:
    - host: smokeping.home.lab
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: tls-smokeping.home.lab
      hosts:
        - smokeping.home.lab

resources:
  limits:
    cpu: "1"
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi